/**
 * COMPONENTS → components table
 */
import { canonicalizeComponentRecord } from '../canonical-source.js';
import { getGameComponentCategory } from '../component-taxonomy.js';
import { fetchComponentWikiEnrichment } from '../sc-wiki-component-enrichment.js';
import { batchUpsert } from './batch.js';
import type { PersistContext } from './context.js';

export async function saveComponents(ctx: PersistContext): Promise<number> {
  const { conn, env, df, loc, onProgress } = ctx;
  const components = df.extractAllComponents();
  if (!components.length) return 0;

  if (loc.isLoaded) {
    for (const c of components) {
      const resolved = loc.resolveOrFallback(c.className, c.name);
      if (resolved) c.name = resolved;
    }
    onProgress?.(`Localized ${components.length} component names`);
  }

  onProgress?.('Enriching component grades/classes from SC Wiki…');
  const wikiEnrichment = await fetchComponentWikiEnrichment(new Set(components.map((c) => String(c.type)).filter(Boolean)));
  let wikiEnriched = 0;
  for (const c of components) {
    const enrichment = wikiEnrichment.get(String(c.className).toLowerCase());
    if (!enrichment) continue;
    if (enrichment.grade) c.grade = enrichment.grade;
    if (enrichment.componentClass) c.componentClass = enrichment.componentClass;
    wikiEnriched++;
  }
  onProgress?.(`Component grades/classes enriched: ${wikiEnriched}/${components.length}`);

  const COMP_COLS = `env, uuid, class_name, name, normalized_name, canonical_component_key,
          type, game_component_category, sub_type, size, grade, component_class, is_bespoke, manufacturer_code,
            mass, hp,
            power_draw, power_base, power_output,
            heat_generation, cooling_rate,
            em_signature, ir_signature,
            weapon_damage, weapon_damage_type, weapon_fire_rate, weapon_range, weapon_speed,
            weapon_ammo_count, weapon_pellets_per_shot, weapon_burst_size,
            weapon_alpha_damage, weapon_dps,
            weapon_damage_physical, weapon_damage_energy, weapon_damage_distortion,
            weapon_damage_thermal, weapon_damage_biochemical, weapon_damage_stun,
            weapon_burst_dps, weapon_sustained_dps,
            weapon_full_damage_range, weapon_zero_damage_range, weapon_heat_per_second,
            weapon_beam_capacity, weapon_beam_regen_cooldown, weapon_beam_dps,
            shield_hp, shield_regen, shield_regen_delay, shield_hardening, shield_faces,
            qd_speed, qd_spool_time, qd_cooldown, qd_fuel_rate, qd_range,
            qd_stage1_accel, qd_stage2_accel,
            qd_tuning_rate, qd_alignment_rate, qd_disconnect_range,
            missile_damage, missile_signal_type, missile_lock_time, missile_speed,
            missile_range, missile_lock_range,
            missile_damage_physical, missile_damage_energy, missile_damage_distortion,
            missile_damage_thermal, missile_damage_biochemical, missile_damage_stun,
            missile_explosion_radius, missile_guidance_mode,
            thruster_max_thrust, thruster_type,
            radar_range, radar_detection_lifetime, radar_tracking_signal,
            radar_ping_range, radar_ping_cooldown,
            cm_ammo_count, cm_type,
            fuel_capacity, fuel_intake_rate,
            emp_damage, emp_radius, emp_charge_time, emp_cooldown,
            qig_jammer_range, qig_snare_radius, qig_charge_time, qig_cooldown,
            mining_speed, mining_range, mining_resistance, mining_instability,
            tractor_max_force, tractor_max_range,
            salvage_speed, salvage_radius, salvage_range,
            gimbal_type, gimbal_max_angle, gimbal_pitch_speed, gimbal_yaw_speed,
            turret_min_pitch, turret_max_pitch, turret_min_yaw, turret_max_yaw,
            rack_count, rack_missile_size,
            shield_downed_regen_delay,
            weapon_heat_per_shot, weapon_charge_time,
            qd_calibration_rate, qd_calibration_delay, qd_calibration_max_angle,
            p4k_path, raw_json`;

  const COMP_CONFLICT = `(uuid, env) DO UPDATE SET
            class_name=EXCLUDED.class_name, name=EXCLUDED.name,
            normalized_name=EXCLUDED.normalized_name,
            canonical_component_key=EXCLUDED.canonical_component_key,
            type=EXCLUDED.type,
            game_component_category=EXCLUDED.game_component_category,
            sub_type=EXCLUDED.sub_type, size=EXCLUDED.size, grade=EXCLUDED.grade,
            component_class=EXCLUDED.component_class,
            is_bespoke=EXCLUDED.is_bespoke,
            manufacturer_code=EXCLUDED.manufacturer_code,
            mass=EXCLUDED.mass, hp=EXCLUDED.hp,
            power_draw=EXCLUDED.power_draw, power_base=EXCLUDED.power_base, power_output=EXCLUDED.power_output,
            heat_generation=EXCLUDED.heat_generation, cooling_rate=EXCLUDED.cooling_rate,
            weapon_damage=EXCLUDED.weapon_damage, weapon_damage_type=EXCLUDED.weapon_damage_type,
            weapon_fire_rate=EXCLUDED.weapon_fire_rate, weapon_range=EXCLUDED.weapon_range,
            weapon_speed=EXCLUDED.weapon_speed, weapon_ammo_count=EXCLUDED.weapon_ammo_count,
            weapon_pellets_per_shot=EXCLUDED.weapon_pellets_per_shot, weapon_burst_size=EXCLUDED.weapon_burst_size,
            weapon_alpha_damage=EXCLUDED.weapon_alpha_damage, weapon_dps=EXCLUDED.weapon_dps,
            weapon_damage_physical=EXCLUDED.weapon_damage_physical, weapon_damage_energy=EXCLUDED.weapon_damage_energy,
            weapon_damage_distortion=EXCLUDED.weapon_damage_distortion,
            weapon_damage_thermal=EXCLUDED.weapon_damage_thermal, weapon_damage_biochemical=EXCLUDED.weapon_damage_biochemical,
            weapon_damage_stun=EXCLUDED.weapon_damage_stun,
            weapon_burst_dps=EXCLUDED.weapon_burst_dps, weapon_sustained_dps=EXCLUDED.weapon_sustained_dps,
            weapon_full_damage_range=EXCLUDED.weapon_full_damage_range, weapon_zero_damage_range=EXCLUDED.weapon_zero_damage_range,
            weapon_heat_per_second=EXCLUDED.weapon_heat_per_second,
            weapon_beam_capacity=EXCLUDED.weapon_beam_capacity, weapon_beam_regen_cooldown=EXCLUDED.weapon_beam_regen_cooldown,
            weapon_beam_dps=EXCLUDED.weapon_beam_dps,
            shield_hp=EXCLUDED.shield_hp, shield_regen=EXCLUDED.shield_regen,
            shield_regen_delay=EXCLUDED.shield_regen_delay, shield_hardening=EXCLUDED.shield_hardening,
            shield_faces=EXCLUDED.shield_faces,
            qd_speed=EXCLUDED.qd_speed, qd_spool_time=EXCLUDED.qd_spool_time,
            qd_cooldown=EXCLUDED.qd_cooldown, qd_fuel_rate=EXCLUDED.qd_fuel_rate,
            qd_range=EXCLUDED.qd_range, qd_stage1_accel=EXCLUDED.qd_stage1_accel,
            qd_stage2_accel=EXCLUDED.qd_stage2_accel,
            qd_tuning_rate=EXCLUDED.qd_tuning_rate, qd_alignment_rate=EXCLUDED.qd_alignment_rate,
            qd_disconnect_range=EXCLUDED.qd_disconnect_range,
            missile_damage=EXCLUDED.missile_damage, missile_signal_type=EXCLUDED.missile_signal_type,
            missile_lock_time=EXCLUDED.missile_lock_time, missile_speed=EXCLUDED.missile_speed,
            missile_range=EXCLUDED.missile_range, missile_lock_range=EXCLUDED.missile_lock_range,
            missile_damage_physical=EXCLUDED.missile_damage_physical, missile_damage_energy=EXCLUDED.missile_damage_energy,
            missile_damage_distortion=EXCLUDED.missile_damage_distortion,
            missile_damage_thermal=EXCLUDED.missile_damage_thermal, missile_damage_biochemical=EXCLUDED.missile_damage_biochemical,
            missile_damage_stun=EXCLUDED.missile_damage_stun,
            missile_explosion_radius=EXCLUDED.missile_explosion_radius,
            missile_guidance_mode=EXCLUDED.missile_guidance_mode,
            thruster_max_thrust=EXCLUDED.thruster_max_thrust, thruster_type=EXCLUDED.thruster_type,
            radar_range=EXCLUDED.radar_range,
            radar_detection_lifetime=EXCLUDED.radar_detection_lifetime,
            radar_tracking_signal=EXCLUDED.radar_tracking_signal,
            radar_ping_range=EXCLUDED.radar_ping_range,
            radar_ping_cooldown=EXCLUDED.radar_ping_cooldown,
            cm_ammo_count=EXCLUDED.cm_ammo_count, cm_type=EXCLUDED.cm_type,
            fuel_capacity=EXCLUDED.fuel_capacity, fuel_intake_rate=EXCLUDED.fuel_intake_rate,
            emp_damage=EXCLUDED.emp_damage, emp_radius=EXCLUDED.emp_radius,
            emp_charge_time=EXCLUDED.emp_charge_time, emp_cooldown=EXCLUDED.emp_cooldown,
            qig_jammer_range=EXCLUDED.qig_jammer_range, qig_snare_radius=EXCLUDED.qig_snare_radius,
            qig_charge_time=EXCLUDED.qig_charge_time, qig_cooldown=EXCLUDED.qig_cooldown,
            mining_speed=EXCLUDED.mining_speed, mining_range=EXCLUDED.mining_range,
            mining_resistance=EXCLUDED.mining_resistance, mining_instability=EXCLUDED.mining_instability,
            tractor_max_force=EXCLUDED.tractor_max_force, tractor_max_range=EXCLUDED.tractor_max_range,
            salvage_speed=EXCLUDED.salvage_speed, salvage_radius=EXCLUDED.salvage_radius, salvage_range=EXCLUDED.salvage_range,
            gimbal_type=EXCLUDED.gimbal_type,
            gimbal_max_angle=EXCLUDED.gimbal_max_angle,
            gimbal_pitch_speed=EXCLUDED.gimbal_pitch_speed, gimbal_yaw_speed=EXCLUDED.gimbal_yaw_speed,
            turret_min_pitch=EXCLUDED.turret_min_pitch, turret_max_pitch=EXCLUDED.turret_max_pitch,
            turret_min_yaw=EXCLUDED.turret_min_yaw, turret_max_yaw=EXCLUDED.turret_max_yaw,
            rack_count=EXCLUDED.rack_count, rack_missile_size=EXCLUDED.rack_missile_size,
            shield_downed_regen_delay=EXCLUDED.shield_downed_regen_delay,
            weapon_heat_per_shot=EXCLUDED.weapon_heat_per_shot,
            weapon_charge_time=EXCLUDED.weapon_charge_time,
            qd_calibration_rate=EXCLUDED.qd_calibration_rate,
            qd_calibration_delay=EXCLUDED.qd_calibration_delay,
            qd_calibration_max_angle=EXCLUDED.qd_calibration_max_angle,
            p4k_path=EXCLUDED.p4k_path,
            raw_json=EXCLUDED.raw_json,
            updated_at=CURRENT_TIMESTAMP`;

  const COL_COUNT = 122; // number of columns above (stats + source metadata + env)

  /** Map a component object to a flat array of values */
  const toCanonicalRow = (c: any): (string | number | boolean | null)[] => {
    const canonical = canonicalizeComponentRecord({
      name: c.name,
      className: c.className,
      type: c.type,
      subType: c.subType,
      grade: c.grade,
      size: c.size,
    });

    return [
      env,
      c.uuid,
      c.className,
      c.name,
      canonical.normalizedName,
      canonical.canonicalComponentKey,
      c.type,
      getGameComponentCategory(c.type),
      c.subType || null,
      c.size ?? null,
      c.grade || null,
      c.componentClass || null,
      c.isBespoke ?? false,
      c.manufacturerCode || null,
      c.mass ?? null,
      c.hp ?? null,
      c.powerDraw ?? null,
      c.powerBase ?? null,
      c.powerOutput ?? null,
      c.heatGeneration ?? null,
      c.coolingRate ?? null,
      c.emSignature ?? null,
      c.irSignature ?? null,
      c.weaponDamage ?? null,
      c.weaponDamageType || null,
      c.weaponFireRate ?? null,
      c.weaponRange ?? null,
      c.weaponSpeed ?? null,
      c.weaponAmmoCount ?? null,
      c.weaponPelletsPerShot ?? 1,
      c.weaponBurstSize ?? null,
      c.weaponAlphaDamage ?? null,
      c.weaponDps ?? null,
      c.weaponDamagePhysical ?? null,
      c.weaponDamageEnergy ?? null,
      c.weaponDamageDistortion ?? null,
      c.weaponDamageThermal ?? null,
      c.weaponDamageBiochemical ?? null,
      c.weaponDamageStun ?? null,
      c.weaponBurstDps ?? null,
      c.weaponSustainedDps ?? null,
      c.weaponFullDamageRange ?? null,
      c.weaponZeroDamageRange ?? null,
      c.weaponHeatPerSecond ?? null,
      c.weaponBeamCapacity ?? null,
      c.weaponBeamRegenCooldown ?? null,
      c.weaponBeamDps ?? null,
      c.shieldHp ?? null,
      c.shieldRegen ?? null,
      c.shieldRegenDelay ?? null,
      c.shieldHardening ?? null,
      c.shieldFaces ?? null,
      c.qdSpeed ?? null,
      c.qdSpoolTime ?? null,
      c.qdCooldown ?? null,
      c.qdFuelRate ?? null,
      c.qdRange ?? null,
      c.qdStage1Accel ?? null,
      c.qdStage2Accel ?? null,
      c.qdTuningRate ?? null,
      c.qdAlignmentRate ?? null,
      c.qdDisconnectRange ?? null,
      c.missileDamage ?? null,
      c.missileSignalType || null,
      c.missileLockTime ?? null,
      c.missileSpeed ?? null,
      c.missileRange ?? null,
      c.missileLockRange ?? null,
      c.missileDamagePhysical ?? null,
      c.missileDamageEnergy ?? null,
      c.missileDamageDistortion ?? null,
      c.missileDamageThermal ?? null,
      c.missileDamageBiochemical ?? null,
      c.missileDamageStun ?? null,
      c.missileExplosionRadius ?? null,
      c.missileGuidanceMode || null,
      c.thrusterMaxThrust ?? null,
      c.thrusterType || null,
      c.radarRange ?? null,
      c.radarDetectionLifetime ?? null,
      c.radarTrackingSignal ?? null,
      c.radarPingRange ?? null,
      c.radarPingCooldown ?? null,
      c.cmAmmoCount ?? null,
      c.cmType || null,
      c.fuelCapacity ?? null,
      c.fuelIntakeRate ?? null,
      c.empDamage ?? null,
      c.empRadius ?? null,
      c.empChargeTime ?? null,
      c.empCooldown ?? null,
      c.qigJammerRange ?? null,
      c.qigSnareRadius ?? null,
      c.qigChargeTime ?? null,
      c.qigCooldown ?? null,
      c.miningSpeed ?? null,
      c.miningRange ?? null,
      c.miningResistance ?? null,
      c.miningInstability ?? null,
      c.tractorMaxForce ?? null,
      c.tractorMaxRange ?? null,
      c.salvageSpeed ?? null,
      c.salvageRadius ?? null,
      c.salvageRange ?? null,
      c.gimbalType || null,
      c.gimbalMaxAngle ?? null,
      c.gimbalPitchSpeed ?? null,
      c.gimbalYawSpeed ?? null,
      c.turretMinPitch ?? null,
      c.turretMaxPitch ?? null,
      c.turretMinYaw ?? null,
      c.turretMaxYaw ?? null,
      c.rackCount ?? null,
      c.rackMissileSize ?? null,
      c.shieldDownedRegenDelay ?? null,
      c.weaponHeatPerShot ?? null,
      c.weaponChargeTime ?? null,
      c.qdCalibrationRate ?? null,
      c.qdCalibrationDelay ?? null,
      c.qdCalibrationMaxAngle ?? null,
      c.p4kPath ?? null,
      c.rawJson ? JSON.stringify(c.rawJson) : null,
    ];
  };

  const rows = components.map(toCanonicalRow);
  const saved = await batchUpsert(conn, `INSERT INTO game.components (${COMP_COLS})`, COMP_CONFLICT, COL_COUNT, rows);

  onProgress?.(`Components: ${saved}/${components.length} (batch INSERT)`);
  return components.length; // all attempted
}
