import type { Metadata } from 'next';
import Link from 'next/link';
import { Bot, BrainCircuit, Code2, Database, ExternalLink, GitBranch, Network, ShieldCheck, Sparkles, Wrench } from 'lucide-react';
import { EarlyAccessNotice } from '@/components/ui/EarlyAccessNotice';
import { PageHeader } from '@/components/ui/PageHeader';
import { PageShell } from '@/components/ui/PageShell';
import { OpenAiButton } from '@/components/ui/OpenAiButton';

export const metadata: Metadata = {
  title: 'About Starvis',
  description:
    'Starvis is an unofficial Star Citizen Database & Toolset in active development, with game data extraction, AI assistance, an external API, Discord bot and corporation tools.',
};

const PLATFORM_LINKS = [
  { href: '/developer', label: 'API Access', icon: Code2 },
  { href: '/api-docs', label: 'Swagger', icon: ExternalLink, external: true },
  { href: '/discord', label: 'Discord Bot', icon: Bot },
  { href: '/legal', label: 'Legal Notice', icon: ShieldCheck },
];

const PRODUCT_AREAS = [
  {
    icon: Database,
    title: 'Unified database',
    text: 'Ships, components, FPS gear, commodities, missions, locations, lore, manufacturers and versioned LIVE/PTU data in one coherent interface.',
  },
  {
    icon: Wrench,
    title: 'Operational tools',
    text: 'Compare, ranking, loadout, FPS, mining, crafting and trade calculators are built on normalized extracted game data.',
  },
  {
    icon: Network,
    title: 'Corporation layer',
    text: 'Fleet manager, corporation bank and tactical planning bring personal and organization workflows into the same Starvis ecosystem.',
  },
  {
    icon: Bot,
    title: 'Discord-ready data',
    text: 'Slash commands expose ships, trade, shops, mining, crafting, missions, lore, status and AI answers directly inside community servers.',
  },
];

const API_POINTS = [
  'Bearer tokens generated by Starvis users for external projects.',
  'Swagger/OpenAPI documentation for ships, items, economy, lore, search, stats and AI endpoints.',
  'Dedicated monitoring for external API traffic, active users, projects and token usage.',
  'Separated public web traffic and external API usage so anonymous browsing does not pollute integration metrics.',
];

const AI_POINTS = [
  'Tool-using Star Citizen assistant connected to Starvis data instead of generic answers.',
  'Context-aware web widget that adapts suggestions to the page currently open.',
  'Discord `/starvis` command for natural-language questions from a server.',
  'Restricted read-only database querying with SQL guardrails for complex rankings, comparisons and cross-domain analysis.',
];

function Panel({ children, className = '' }: { children: React.ReactNode; className?: string }) {
  return <section className={`sci-panel p-5 ${className}`}>{children}</section>;
}

function Pill({ children }: { children: React.ReactNode }) {
  return <span className="rounded-sm border border-cyan-900/50 bg-cyan-950/20 px-2 py-1 font-mono-sc text-[10px] uppercase tracking-widest text-cyan-400">{children}</span>;
}

export default function AboutPage() {
  return (
    <PageShell size="xl" className="p-4 md:p-6">
      <PageHeader
        eyebrow="Platform"
        title="About Starvis"
        subtitle="Unofficial Star Citizen Database & Toolset in active development."
        actions={
          <div className="flex flex-wrap gap-2">
            {PLATFORM_LINKS.map(({ href, label, icon: Icon, external }) =>
              external ? (
                <a key={href} href={href} target="_blank" rel="noreferrer" className="sci-btn-ghost px-3 py-2 text-xs">
                  <Icon size={13} />
                  {label}
                </a>
              ) : (
                <Link key={href} href={href} className="sci-btn-ghost px-3 py-2 text-xs">
                  <Icon size={13} />
                  {label}
                </Link>
              ),
            )}
          </div>
        }
      />

      <EarlyAccessNotice className="mb-4">
        Starvis is in active development. Some extracted fields, calculated values and AI-assisted answers can be incomplete or corrected as validation improves.
      </EarlyAccessNotice>

      <Panel className="overflow-hidden">
        <div className="grid gap-5 lg:grid-cols-[minmax(0,1.25fr)_minmax(300px,0.75fr)]">
          <div>
            <div className="mb-4 flex flex-wrap gap-2">
              <Pill>Active development</Pill>
              <Pill>Unofficial project</Pill>
              <Pill>AI + API first</Pill>
            </div>
            <h2 className="font-orbitron text-2xl font-black uppercase tracking-widest text-cyan-300">
              One hub instead of scattered tools
            </h2>
            <p className="mt-3 max-w-3xl font-rajdhani text-base leading-relaxed text-slate-400">
              Starvis centralizes Star Citizen data and practical tools so players, organizations and developers do not have to jump between dozens of disconnected websites,
              spreadsheets, Discord snippets and partial calculators. It combines extracted game data, RSI website data, a web interface, corporation tools, a Discord bot,
              an external API and an AI assistant in one coherent platform.
            </p>
          </div>
          <div className="rounded-sm border border-cyan-900/40 bg-cyan-950/10 p-4">
            <p className="mb-2 flex items-center gap-2 font-orbitron text-[10px] font-bold uppercase tracking-widest text-cyan-400">
              <GitBranch size={13} />
              Data approach
            </p>
            <p className="font-rajdhani text-sm leading-relaxed text-slate-400">
              Starvis is built from extraction, normalization and analysis of game and public RSI data. The goal is not to copy community projects, but to make Starvis data reusable,
              documented and reliable enough for integrations.
            </p>
          </div>
        </div>
      </Panel>

      <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-4">
        {PRODUCT_AREAS.map(({ icon: Icon, title, text }) => (
          <Panel key={title}>
            <Icon size={18} className="mb-3 text-cyan-400" />
            <h3 className="font-orbitron text-sm font-bold uppercase tracking-widest text-slate-200">{title}</h3>
            <p className="mt-2 font-rajdhani text-sm leading-relaxed text-slate-500">{text}</p>
          </Panel>
        ))}
      </div>

      <div className="grid gap-4 lg:grid-cols-2">
        <Panel>
          <div className="mb-4 flex items-center gap-2 border-b border-slate-800/70 pb-3">
            <Code2 size={15} className="text-cyan-400" />
            <h2 className="font-orbitron text-[10px] font-bold uppercase tracking-widest text-slate-400">External API</h2>
          </div>
          <p className="font-rajdhani text-sm leading-relaxed text-slate-400">
            Starvis is designed as a data platform, not only a website. The external API lets approved users build bots, tools, audits, dashboards or organization workflows on top of the same normalized data.
          </p>
          <ul className="mt-4 space-y-2">
            {API_POINTS.map((point) => (
              <li key={point} className="flex gap-2 font-rajdhani text-sm text-slate-500">
                <span className="mt-1 h-1.5 w-1.5 shrink-0 rounded-full bg-cyan-500" />
                {point}
              </li>
            ))}
          </ul>
          <div className="mt-4 flex flex-wrap gap-2">
            <Link href="/developer" className="sci-btn-primary px-3 py-2 text-xs">
              Open API Access
            </Link>
            <a href="/api-docs" target="_blank" rel="noreferrer" className="sci-btn-ghost px-3 py-2 text-xs">
              Swagger
            </a>
          </div>
        </Panel>

        <Panel>
          <div className="mb-4 flex items-center gap-2 border-b border-slate-800/70 pb-3">
            <BrainCircuit size={15} className="text-violet-400" />
            <h2 className="font-orbitron text-[10px] font-bold uppercase tracking-widest text-slate-400">AI data assistant</h2>
          </div>
          <p className="font-rajdhani text-sm leading-relaxed text-slate-400">
            The Starvis AI layer is meant to become the natural-language interface for the platform: asking questions, comparing options, summarizing data and guiding users toward the right tool or endpoint.
          </p>
          <ul className="mt-4 space-y-2">
            {AI_POINTS.map((point) => (
              <li key={point} className="flex gap-2 font-rajdhani text-sm text-slate-500">
                <span className="mt-1 h-1.5 w-1.5 shrink-0 rounded-full bg-violet-500" />
                {point}
              </li>
            ))}
          </ul>
          <div className="mt-4 flex flex-wrap gap-2">
            <OpenAiButton
              prompt="Show me what the Starvis AI assistant can do across ships, economy, lore, corporations, Discord and the external API."
              className="rounded-sm border border-violet-800/50 bg-violet-950/20 px-3 py-2 font-mono-sc text-xs text-violet-300 transition-colors hover:border-violet-500/70 hover:bg-violet-950/40"
            >
              <span className="inline-flex items-center gap-2">
                <Sparkles size={13} />
                Ask Starvis AI
              </span>
            </OpenAiButton>
            <Link href="/discord" className="sci-btn-ghost px-3 py-2 text-xs">
              Discord AI command
            </Link>
          </div>
        </Panel>
      </div>

      <Panel>
        <div className="grid gap-4 md:grid-cols-[220px_minmax(0,1fr)]">
          <div>
            <p className="font-orbitron text-[10px] font-bold uppercase tracking-widest text-amber-400">Important notice</p>
            <p className="mt-2 font-mono-sc text-[10px] leading-relaxed text-slate-600">Non official, active development, data quality improving continuously.</p>
          </div>
          <p className="font-rajdhani text-sm leading-relaxed text-slate-400">
            Starvis is an independent community project and is not affiliated with, endorsed by, sponsored by or officially connected to Cloud Imperium Games, Roberts Space Industries or their affiliates.
            Game data can be incomplete, outdated or inaccurate while extraction and validation improve.
          </p>
        </div>
      </Panel>
    </PageShell>
  );
}
