export const API_BASE = '/api/v1';

export const VARIANT_TYPE_LABELS: Record<string, string> = {
  standard: 'Standard',
  collector: 'Collector',
  wikelo: 'Wikelo',
  pyam_exec: 'PyAM / Exec',
};

/** Internal DB type → human-readable game label */
export const COMPONENT_TYPE_LABELS: Record<string, string> = {
  WeaponGun: 'Gun',
  WeaponMissile: 'Missile',
  Shield: 'Shield',
  QuantumDrive: 'Quantum Drive',
  PowerPlant: 'Power Plant',
  Cooler: 'Cooler',
  FuelTank: 'Fuel Tank',
  FuelIntake: 'Fuel Intake',
  Thruster: 'Thruster',
  Radar: 'Radar',
  Countermeasure: 'Countermeasure',
  EMP: 'EMP',
  MissileRack: 'Missile Rack',
  MiningLaser: 'Mining Laser',
  TractorBeam: 'Tractor Beam',
  SalvageHead: 'Salvage Head',
  LifeSupport: 'Life Support',
  QuantumInterdictionGenerator: 'Quantum Interdiction',
  LandingSystem: 'Landing System',
  Gimbal: 'Gimbal',
  Turret: 'Turret',
  TurretUnmanned: 'Unmanned Turret',
  SelfDestruct: 'Self Destruct',
  Scanner: 'Scanner',
  Missile: 'Missile',
  Torpedo: 'Torpedo',
  Bomb: 'Bomb',
};

export const COMPONENT_TYPE_COLORS: Record<string, string> = {
  WeaponGun: 'text-red-400',
  WeaponMissile: 'text-orange-400',
  Shield: 'text-blue-400',
  QuantumDrive: 'text-purple-400',
  PowerPlant: 'text-yellow-400',
  Cooler: 'text-cyan-400',
  FuelTank: 'text-green-400',
  FuelIntake: 'text-green-300',
  Thruster: 'text-amber-400',
  Radar: 'text-indigo-400',
  Countermeasure: 'text-teal-400',
  EMP: 'text-fuchsia-400',
  MissileRack: 'text-orange-300',
  MiningLaser: 'text-emerald-400',
  TractorBeam: 'text-sky-400',
  SalvageHead: 'text-lime-400',
  LifeSupport: 'text-rose-400',
  QuantumInterdictionGenerator: 'text-violet-400',
  LandingSystem: 'text-slate-300',
  Gimbal: 'text-slate-400',
  Turret: 'text-red-300',
  TurretUnmanned: 'text-red-200',
  SelfDestruct: 'text-rose-600',
  Scanner: 'text-teal-400',
  Missile: 'text-orange-400',
  Torpedo: 'text-orange-500',
  Bomb: 'text-rose-500',
};

/** FPS item type → human-readable game label (matches SC inventory names) */
export const ITEM_TYPE_LABELS: Record<string, string> = {
  FPS_Weapon: 'Weapon',
  Armor: 'Armor',
  Undersuit: 'Undersuit',
  Clothing: 'Clothing',
  Gadget: 'Gadget',
  Tool: 'Tool',
  Consumable: 'Consumable',
  Attachment: 'Attachment',
  Magazine: 'Magazine',
};
