%%{init: {'theme': 'base', 'themeVariables': {'fontSize': '13px', 'fontFamily': 'Arial'}, 'sequence': {'actorFontSize': 13, 'messageFontSize': 12, 'mirrorActors': false, 'useMaxWidth': true, 'boxMargin': 8, 'noteMargin': 8}}}%%
sequenceDiagram
    actor U as Utilisateur
    participant IHM as Next.js
    participant API as API Express
    participant DB as PostgreSQL

    U->>IHM: POST /login {email, password}
    IHM->>API: POST /auth/login
    API->>DB: SELECT user WHERE email = ?
    DB-->>API: User {passwordHash, role}

    alt Identifiants invalides
        API-->>IHM: 401 Unauthorized
        IHM-->>U: Affiche erreur
    else Succès
        API->>API: bcrypt.compare(pwd, hash)
        API->>API: jwt.sign({uuid, role}, 7j)
        API-->>IHM: 200 OK {token, user}
        IHM->>IHM: Stocke token (cookie httpOnly)
        IHM-->>U: Redirige vers dashboard
    end

    Note over U,DB: Accès à une route protégée
    U->>IHM: GET /admin/users
    IHM->>API: GET /admin/users\n[Authorization: Bearer token]
    API->>API: verifyJWT(token)

    alt Token invalide / expiré
        API-->>IHM: 401 Unauthorized
        IHM-->>U: Redirige vers /login
    else Role insuffisant
        API-->>IHM: 403 Forbidden
        IHM-->>U: Accès refusé
    else Admin confirmé
        API->>DB: SELECT users
        DB-->>API: users[]
        API-->>IHM: 200 OK {data: users[]}
        IHM-->>U: Affiche panneau admin
    end
